Repository yegor256/cactoos, pull requests merged in 2020-07, with the labels that each got.

#1402 For #1313: Additional ctors for `Filtered`
  src/main/java/org/cactoos/iterable/Filtered.java
  src/main/java/org/cactoos/iterator/Filtered.java
  src/test/java/org/cactoos/iterable/FilteredTest.java
  src/test/java/org/cactoos/scalar/ReducedTest.java
Labels: role/REV, scope

#1412 (#1411) Cleanup pom, bump parent and add todo for junit 5
  pom.xml
  src/test/java/org/cactoos/map/NoNullsTest.java
Labels: role/REV, scope

#1418 For #1396: Partial migration to `Assertion` from `cactoos-matchers`
  src/main/java/org/cactoos/iterable/IterableOf.java
  src/main/java/org/cactoos/list/Shuffled.java
  src/test/java/org/cactoos/func/FuncWithFallbackTest.java
  src/test/java/org/cactoos/func/IoCheckedBiFuncTest.java
  src/test/java/org/cactoos/func/IoCheckedFuncTest.java
  src/test/java/org/cactoos/func/IoCheckedProcTest.java
  src/test/java/org/cactoos/func/ProcOfTest.java
  src/test/java/org/cactoos/func/RepeatedTest.java
  src/test/java/org/cactoos/func/RunnableOfTest.java
  src/test/java/org/cactoos/func/SolidBiFuncTest.java
  src/test/java/org/cactoos/func/SolidFuncTest.java
  src/test/java/org/cactoos/func/StickyBiFuncTest.java
  src/test/java/org/cactoos/func/StickyFuncTest.java
  src/test/java/org/cactoos/func/SyncFuncTest.java
  src/test/java/org/cactoos/func/TimedFuncTest.java
  src/test/java/org/cactoos/func/UncheckedBiFuncTest.java
  src/test/java/org/cactoos/package-info.java
  src/test/java/org/cactoos/scalar/package-info.java
Labels: 0crat/role/DEV, 0crat/scope

#1419 Added a ForEachWithIndex class
  src/main/java/org/cactoos/func/ForEachWithIndex.java
  src/test/java/org/cactoos/func/ForEachWithIndexTest.java
Labels: 0crat/role/REV, 0crat/scope
